### ISSUE TITLE
Empty messages

### ISSUE THREAD

**Issue by skywave** [StichtingOpenGeo/openebs2#58]
Should we allow empty\* messages?
I can sort of see a point for it in case of OVERRULE messages (to just get the screen dark) but it 
- (either 0 characters or Strings with just spaces)

**Comment by skinkie** [comment]
Lets allow an empty text for "OVERRULE".

**Comment by Baasje85** [comment]
I believe this was already fixed...
When I select 'overrule', it is send (at least to database / message overview):

![image](https://user-images.githubusercontent.com/51262792/80704116-4ac7b500-8ae4-11ea-9f71-8803b086fa15.png)

Otherwise I get the error message:
![image](https://user-images.githubusercontent.com/51262792/80704160-6206a280-8ae4-11ea-9ee4-a420aea7048a.png)


Might be an idea to edit the message "geen tekst of overschrijf bericht" to only: "overschrijfbericht", since "geen tekst" is not an option apart from the overrule-messages.

**Comment by skinkie** [comment]
I think this is not possible because an external incomming message over KV8generalmessage _might_ be empty. Thanks for checking if this issues still persisted. Closing for now.
